[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/src/",
  "solady/=lib/solady/src/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
  "halmos-cheatcodes/=lib/halmos-cheatcodes/src/",
]

gas_reports = ["*"]

[invariant]
runs = 256
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
